name: Build sourceacademy.org
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and deploy sourceacademy.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: Setup Sentry CLI
      run: |
        curl -sL https://sentry.io/get-cli/ | INSTALL_DIR=. bash
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - id: get-time
      run: echo "::set-output name=time::$(date -Iseconds)"
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: 1-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          1-${{ runner.os }}-yarn-
    - uses: actions/cache@v2
      id: build-cache
      with:
        path: node_modules/.cache
        key: 1-${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          1-${{ runner.os }}-build-
    - name: yarn install and build
      run: |
        yarn install
        yarn run build
      env:
        VITE_URL_SHORTENER_SIGNATURE: ${{ secrets.VITE_URL_SHORTENER_SIGNATURE }}
        VITE_URL_SHORTENER_BASE: ${{ secrets.VITE_URL_SHORTENER_BASE }}
        VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
        VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
        VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
        VITE_GOOGLE_APP_ID: ${{ secrets.VITE_GOOGLE_APP_ID }}
        VITE_PLAYGROUND_ONLY: "TRUE"
        VITE_ENABLE_GITHUB_ASSESSMENTS: "TRUE"
        VITE_VERSION: ${{ format('{0}-{1}', github.sha, steps.get-time.outputs.time) }}
        VITE_ENVIRONMENT: "pages"
        VITE_MODULE_BACKEND_URL: https://source-academy.github.io/modules
        VITE_SHAREDB_BACKEND_URL: ${{ secrets.VITE_SHAREDB_BACKEND_URL }}
        PUBLIC_URL: "https://sourceacademy.org"
        VITE_GITHUB_OAUTH_PROXY_URL: ${{ secrets.VITE_GITHUB_OAUTH_PROXY_URL }}
        VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}
    - name: Create Sentry release
      working-directory: build
      run: |
        SENTRY_RELEASE="cadet-frontend@$VITE_VERSION"
        "$GITHUB_WORKSPACE/sentry-cli" releases new -p "$SENTRY_PROJECT" "$SENTRY_RELEASE"
        "$GITHUB_WORKSPACE/sentry-cli" releases set-commits --auto "$SENTRY_RELEASE"
        "$GITHUB_WORKSPACE/sentry-cli" releases files "$SENTRY_RELEASE" upload-sourcemaps --url-prefix '~/static/js' --rewrite static/js
        "$GITHUB_WORKSPACE/sentry-cli" releases finalize "$SENTRY_RELEASE"
        "$GITHUB_WORKSPACE/sentry-cli" releases deploys "$SENTRY_RELEASE" new -e pages
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: sourceacademy
        SENTRY_PROJECT: cadet-frontend
        VITE_VERSION: ${{ format('{0}-{1}', github.sha, steps.get-time.outputs.time) }}
    - name: Remove sourcemaps
      working-directory: build
      run: |
        find -name '*.map' -print -delete
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: source-academy/sourceacademy.org
        deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_dir: ./build
        publish_branch: master
        force_orphan: true
